config/routes.rb
Personnel::Application.routes.draw do

  resources :taxi_routes, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resource :user do
      get :delivery, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_crop, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :notify_address, on: :collection
      get :notify_cell, on: :collection
      get :crop, on: :member
      get :find, on: :collection
      get :list, on: :collection
      put :send_notify_address, on: :collection
      put :send_notify_cell, on: :collection
  end

  resources :users do
    get :view, on: :member
    get :by_department, on: :collection
  end

  resources :addresses do
    get :make_primary, on: :member
    get :map, on: :member
    put :update_map, on: :member
  end

  resources :shifts do
    get :close_old, on: :collection
    get :check, on: :collection
    get :check_department_for_identifier, on: :member
    get :check_fired_permissions, on: :collection
  end
  resource :schedule do
    post :update_cell, on: :collection
    post :toggle_exclude, on: :collection
  end
  resources :vacation_requests
  resources :events do
    get :start_shift, on: :collection
    get :end_shift, on: :collection
    post :create_shift, on: :collection
    get :available_shift_numbers, on: :collection
    get :new_late_coming, on: :collection
    post :create_late_coming, on: :collection
    get :processed_by_person, on: :collection
    get :vacations, on: :collection
    get :new_self_score, on: :collection
    get :new_shift_leader_score, on: :collection
    post :create_self_score, on: :collection
    post :create_shift_leader_score, on: :collection
    get :list, on: :collection
  end
  resources :user_vehicles
  resources :late_comings
  resources :birthdays
  devise_for :admins, :controllers => { :registrations => "admin_registrations" }
  namespace :admin do
    root :to => "users#index"
    resources :departments, :categories, :schedule_statuses, :schedule_shifts, :permissions, :logs
    resources :late_comings do
      put :release, on: :collection
    end
    resources :admins do
      get :settings_edit, on: :collection
      put :settings_update, on: :collection
    end
    resource :schedule do
      get :show_users, on: :member
    end
    resources :schedule_cells do
      put :mass_update, on: :collection
      get :change, on: :collection
      get :batch_new, on: :collection
      put :batch_update, on: :collection
    end
    resources :shifts do
      get :available_shift_numbers, on: :collection
      get :missed, on: :collection
    end
    resources :events do
      get :processed_total, on: :collection
      get :processed_by_person, on: :collection
      get :vacations, on: :collection
      get :processed_by_day_of_week, on: :collection
      get :self_scores, on: :collection
      get :self_scores_grouped, on: :collection
      get :shift_leader_scores, on: :collection
      get :shift_leader_scores_grouped, on: :collection
    end
    resources :schedule_templates do
      post :set_visibility, on: :member
      get :select_users, on: :member
      put :update_editable_users, on: :member
      get :check_day, on: :member
      get :check_day_detailed, on: :member
      get :check_month, on: :member
      get :default_norms, on: :member
      get :user_norms, on: :member
      post :update_default_norms, on: :member
      post :update_user_norms, on: :member
      get :check_shift_interval, on: :member
    end

    resources :addresses do
      get :make_primary, on: :member
      get :map, on: :member
      put :update_map, on: :member
    end

    resources :users do
      get :delivery, on: :collection
      get :list, on: :collection
      get :find, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_permissions, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :crop, on: :member
      put :update_crop, on: :member
      put :clear_avatar, on: :member
      get :working_shifts, on: :collection
      get :t_shirts, on: :collection
      get :get_for_department, on: :collection
      put :update_for_department, on: :collection
      get :fire_reasons, on: :collection
      get :fired_people, on: :collection
    end

    resources :birthdays
    resources :fire_reasons
    resources :vacation_requests, only: [:index] do
      put :approve, on: :member
      put :decline, on: :member
    end
  end

  namespace :api do
    resources :departments, only: [:index, :show]
    resources :users, only: [:index] do
      get :rate, on: :collection
      get :rates, on: :collection
      get :feedbacks, on: :collection
      get :shifts, on: :collection
      get :nc_report, on: :collection
    end
    resources :leader_shifts, only: [:index]
  end

  root :to => "home#index"

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :check_permissions, :except => :delivery
  layout 'admin'

  def check_permissions
    redirect_to delivery_admin_users_path unless current_admin.super_user? || !current_admin.departments.empty?
  end

  def index
    if !params[:sort_order]
      params[:date_from_check] = "1"
    end
    params[:date_from] = (DateTime.current - 2.hour).to_formatted_s(:date_and_time)  if !params[:date_from]
    params[:date_to] = DateTime.current.to_formatted_s(:date_and_time)  if !params[:date_to]
    params[:user_ids] = [params[:user_id]] unless params[:user_id].blank?
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15

    @events = Event.joins('JOIN users ON events.user_id = users.id').search(params, current_admin.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events }
    end
  end

  def show

  end

  def new
    @event = Event.new
    render :layout => false
  end

  def edit
    @event = Event.find(params[:id])
    render :layout => false
  end

  def create
    @event = Event.new(params[:event])
    @event.ip_address = Event.ip2int(request.remote_ip)

    if @event.save
      render(:update) do |page|
        page["#overlay"].dialog("close")
        page.call 'app.reload'
      end
    else
      message = '<p>' + @event.errors.full_messages.join('</p><p>') + '</p>'
      render(:update) do |page|
        page['#event_flash'].parents(0).show
        page['#event_flash'].html message
      end
    end

  end

  def update
    @event = Event.find(params[:id])
    @event.ip_address = Event.ip2int(request.remote_ip)

    if @event.update_attributes(params[:event])
      render(:update) do |page|
        page["#overlay"].dialog("close")
        page.call 'app.reload'
      end
    else
      message = '<p>' + @event.errors.full_messages.join('</p><p>') + '</p>'
      render(:update) do |page|
        page['#event_flash'].parents(0).show
        page['#event_flash'].html message
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.xml { head :ok }
    end
  end

  def processed_total
    params[:date_from] = (Date.current - 1.month).to_formatted_s(:date_only)  if !params[:date_from]
    params[:date_to] = Date.current.to_formatted_s(:date_only)  if !params[:date_to]
    @events = Event.processed_total(params, current_admin, true)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events }
    end
  end

  def processed_by_person
    params[:date_from] = (Date.current - 1.month).to_formatted_s(:date_and_time)  if !params[:date_from]
    params[:date_to] = DateTime.current.utc.to_formatted_s(:date_and_time)  if !params[:date_to]
    params[:user_ids] = [params[:user_id]] unless params[:user_id].blank?
    @events = Event.processed_by_person(params, current_admin)

    if params[:export]
      @categories = @events.map{|ev| ev.name}.uniq.sort
      @lines = {}
      @events.each do |event|
        @lines[event.username] ||= {}
        @lines[event.username][event.name] = event.total
      end
      headers['Content-Type'] = "application/vnd.ms-excel"
      headers['Content-Disposition'] = 'attachment; filename="processed_by_person.xls"'
      headers['Cache-Control'] = ''
      render 'export_processed_by_person', :layout => false
    end
  end

  def vacations

    params[:date_from] ||= Date.new(Date.current.year, 1).beginning_of_month.to_formatted_s(:date_and_time)
    params[:date_to] ||= Date.current.to_formatted_s(:date_and_time)
    params[:user_ids] = [params[:user_id]] unless params[:user_id].blank?

    @events = {}
    ScheduleTemplate.vacations(params, current_admin).each do |line|
      @events[line.username] ||= {}
      @events[line.username]["#{line.year}, #{line.month}"] ||= {}
      @events[line.username]["#{line.year}, #{line.month}"][line.additional_attributes] = line.total
    end
  end

  def processed_by_day_of_week
    params[:date_from] = (Date.current - 1.month).to_formatted_s(:date_only)  if !params[:date_from]
    params[:date_to] = Date.current.to_formatted_s(:date_only)  if !params[:date_to]
    @events = Event.processed_by_day_of_week(params, current_admin, true)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events }
    end
  end

  def self_scores
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15
    @scores = SelfScore.search(params, current_admin)
    @average = SelfScore.search_average(params, current_admin).avg_score
  end

  def self_scores_grouped
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15
    @scores = SelfScore.search_grouped(params, current_admin)
    if params[:export]
      headers['Content-Type'] = "application/vnd.ms-excel"
      headers['Content-Disposition'] = 'attachment; filename="self_scores.xls"'
      headers['Cache-Control'] = ''
      render 'export_self_scores_grouped', :layout => false
    end
  end


  def shift_leader_scores
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15
    @scores = ShiftLeaderScore.search(params, current_admin)
    @average = ShiftLeaderScore.search_average(params, current_admin).avg_score
  end

  def shift_leader_scores_grouped
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15
    @scores = ShiftLeaderScore.search_grouped(params, current_admin)
    if params[:export]
      headers['Content-Type'] = "application/vnd.ms-excel"
      headers['Content-Disposition'] = 'attachment; filename="shift_leader_scores.xls"'
      headers['Cache-Control'] = ''
      render 'export_shift_leader_scores_grouped', :layout => false
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_sidebar.html.haml
.block.notice
  %h3 Tips
  .content
    %p You can check all Time Report events added by users here.

app/views/admin/events/_sidebar_processed_by_day_of_week.html.haml
.block.notice
  %h3 Tips
  .content
    %p You can check the number of events added by users in Time Report according to the days of the week here.

app/views/admin/events/_sidebar_processed_by_person.html.haml
.block.notice
  %h3 Tips
  .content
    %p All events added by users in their Time Report can be checked here.

app/views/admin/events/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_events_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_event_path, :class => 'modal_dialog'
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Events
    .inner
      = form_tag(admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              = check_box_tag :date_from_check, 1, params[:date_from_check]
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'datetime_select'
            %td
              &nbsp;
            %td
              = check_box_tag :date_to_check, 1, params[:date_to_check]
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'datetime_select'
            %td
              &nbsp;
            %td
              per page
              = text_field_tag 'per_page', params[:per_page], :style => "width:30px"
            %td
              &nbsp;
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
      %table.table
        %tr
          %th
            = t("activerecord.attributes.admin_event.datetime", :default => t("activerecord.labels.datetime", :default => "DateTime"))
          %th
            = t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th
            = t("activerecord.attributes.category.name", :default => t("activerecord.labels.category", :default => "Category"))
          %th
            = t("activerecord.attributes.admin_event.description", :default => t("activerecord.labels.description", :default => "Description"))
          %th.last &nbsp;
        - @events.each do |event|
          %tr{:class => cycle("odd", "even")}
            %td
              = event.eventtime.to_formatted_s(:date_and_time)
            %td
              = event.user_full_name
            %td
              = event.category_name
            %td
              = event.description
            %td.last
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_event_path(event), :class => "modal_dialog"} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_event_path(event), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure you would like to delete #{event.category_name}:#{event.description} event?")}"}
      .actions-bar.wat-cf
        .actions
        = will_paginate @events
- content_for :sidebar, render(:partial => 'sidebar')
%div.modal#overlay
  %div.contentWrap

app/views/admin/events/processed_by_person.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Processed: By Person
    .inner
      = form_tag(processed_by_person_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              = select_tag 'categories[]', options_for_select(Category.report_selection_by_admin(current_admin.id), params[:categories]),
              { :multiple => true, :size => 5, :style => "font-size:10px" }
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id, params[:department_id]), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'datetime_select'
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'datetime_select'
            %td
              &nbsp;
            %td
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
              %button.button{:type => "submit", :name => "export", :value => "export"}
                = image_tag("web-app-theme/icons/table_go.png", :alt => "#{t("web-app-theme.export", :default => "Export")}")
                = t("web-app-theme.export", :default => "Export")
      %table.table
        - user = ''
        - @events.each do |event|
          - if user != event.username
            - user = event.username
            %tr
              %td{:colspan => 6}
                %h3= user
            %tr
              %th
                = t("activerecord.attributes.admin_event.category", :default => t("activerecord.labels.category", :default => "Category"))
              %th
                = t("activerecord.attributes.admin_event.count", :default => t("activerecord.labels.count", :default => "Count"))
          %tr{:class => cycle("odd", "even")}
            %td
              = event.name
            %td
              = event.total
- content_for :sidebar, render(:partial => 'sidebar_processed_by_person')
%div.contentWrap

app/views/admin/events/processed_total.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Processed: Total
    .inner
      = form_tag(processed_total_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'date_select'
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'date_select'
            %td
              &nbsp;
            %td
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
      %table.table
        %tr
          %th
            = t("activerecord.attributes.admin_event.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th
            = t("activerecord.attributes.admin_user.total", :default => t("activerecord.labels.total", :default => "Total"))
        - @events.each do |event|
          %tr{:class => cycle("odd", "even")}
            %td
              = event.name
            %td
              = event.total
- content_for :sidebar, render(:partial => 'sidebar')
%div.contentWrap

app/views/admin/events/self_scores.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Self-Assessments
    .inner
      = form_tag(self_scores_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id, params[:department_id]), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              = check_box_tag :date_from_check, 1, params[:date_from_check]
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'date_select'
            %td
              &nbsp;
            %td
              = check_box_tag :date_to_check, 1, params[:date_to_check]
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'date_select'
            %td
              &nbsp;
            %td
              = check_box_tag :with_comments, 1, params[:with_comments]
            %td with comments

            %td
              &nbsp;
            %td
              per page
              = text_field_tag 'per_page', params[:per_page], :style => "width:30px"
            %td
              &nbsp;
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
      %table.table
        %tr
          %th
            = t("activerecord.attributes.admin_self_score.date", :default => t("activerecord.labels.date", :default => "Date"))
          %th{:sort => 'full_name', :class => 'sortable'}
            = t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th{:sort => 'score', :class => 'sortable'}
            = t("activerecord.attributes.admin_self_score.score", :default => t("activerecord.labels.rating", :default => "Rating"))
          %th
            = t("activerecord.attributes.admin_self_score.comments", :default => t("activerecord.labels.comments", :default => "Comments"))
        - @scores.each do |line|
          %tr{:class => cycle("odd", "even")}
            %td
              = line.score_date.to_formatted_s(:date)
            %td
              = line.user_full_name
            %td
              = line.score
            %td
              = line.comment
        %tr
          %td{:colspan => 2}
          %td
            %b
              = "Average: %.2f" % @average if @average
          %td
      .actions-bar.wat-cf
        .actions
        = will_paginate @scores
%div.modal#overlay
  %div.contentWrap

app/views/admin/events/self_scores_grouped.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Self-Assessments
    .inner
      = form_tag(self_scores_grouped_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id, params[:department_id]), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              = check_box_tag :date_from_check, 1, params[:date_from_check]
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'date_select'
            %td
              &nbsp;
            %td
              = check_box_tag :date_to_check, 1, params[:date_to_check]
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'date_select'
            %td
              &nbsp;
            %td
              per page
              = text_field_tag 'per_page', params[:per_page], :style => "width:30px"
            %td
              &nbsp;
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
              %button.button{:type => "submit", :name => "export", :value => "export"}
                = image_tag("web-app-theme/icons/table_go.png", :alt => "#{t("web-app-theme.export", :default => "Export")}")
                = t("web-app-theme.export", :default => "Export")
      %table.table
        %tr
          %th{:sort => 'full_name', :class => 'sortable'}
            = t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th{:sort => 'score', :class => 'sortable'}
            = t("activerecord.attributes.admin_self_score.score", :default => t("activerecord.labels.rating", :default => "Rating"))
        - @scores.each do |line|
          %tr{:class => cycle("odd", "even")}
            %td
              = line.user_full_name
            %td
              = "%.2f" % line.avg_score
      .actions-bar.wat-cf
        .actions
        = will_paginate @scores
%div.modal#overlay
  %div.contentWrap

app/views/admin/events/shift_leader_scores.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Shift Leader Score
    .inner
      = form_tag(shift_leader_scores_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id, params[:department_id]), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              = check_box_tag :date_from_check, 1, params[:date_from_check]
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'date_select'
            %td
              &nbsp;
            %td
              = check_box_tag :date_to_check, 1, params[:date_to_check]
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'date_select'
            %td
              &nbsp;
            %td
              per page
              = text_field_tag 'per_page', params[:per_page], :style => "width:30px"
            %td
              &nbsp;
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
      %table.table
        %tr
          %th
            = t("activerecord.attributes.admin_self_score.date", :default => t("activerecord.labels.date", :default => "Date"))
          %th{:sort => 'full_name', :class => 'sortable'}
            = t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th{:sort => 'score', :class => 'sortable'}
            = t("activerecord.attributes.admin_self_score.score", :default => t("activerecord.labels.rating", :default => "Rating"))
          %th
            = t("activerecord.attributes.admin_self_score.comments", :default => t("activerecord.labels.comments", :default => "Comments"))
        - @scores.each do |line|
          %tr{:class => cycle("odd", "even")}
            %td
              = line.shift_date.to_formatted_s(:date)
              = "##{line.shift_number}"
            %td
              = line.shift_leader.full_name
            %td
              = line.score
            %td
              = line.comment
        %tr
          %td{:colspan => 2}
          %td
            %b
              = "Average: %.2f" % @average if @average
          %td
      .actions-bar.wat-cf
        .actions
        = will_paginate @scores
%div.modal#overlay
  %div.contentWrap

app/views/admin/events/shift_leader_scores_grouped.haml
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Shift Leader Score
    .inner
      = form_tag(shift_leader_scores_grouped_admin_events_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              &nbsp;
            %td
              Department
              = select_tag :department_id, options_for_select(Department.selection_by_admin(current_admin.id, true), params[:department_id]), { :include_blank => true }
            %td#users_select
              User
              = select_tag :user_id, options_for_select(User.selection_by_admin(current_admin.id, params[:department_id]), params[:user_id]), { :include_blank => true }
            %td
              &nbsp;
            %td
              = check_box_tag :date_from_check, 1, params[:date_from_check]
            %td
              &nbsp;
            %td
              From
              = text_field_tag 'date_from', params[:date_from], :class => 'date_select'
            %td
              &nbsp;
            %td
              = check_box_tag :date_to_check, 1, params[:date_to_check]
            %td
              &nbsp;
            %td
              To
              = text_field_tag 'date_to', params[:date_to], :class => 'date_select'
            %td
              &nbsp;
            %td
              per page
              = text_field_tag 'per_page', params[:per_page], :style => "width:30px"
            %td
              &nbsp;
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/find.png", :alt => "#{t("web-app-theme.find", :default => "Find")}")
                = t("web-app-theme.find", :default => "Find")
              %button.button{:type => "submit", :name => "export", :value => "export"}
                = image_tag("web-app-theme/icons/table_go.png", :alt => "#{t("web-app-theme.export", :default => "Export")}")
                = t("web-app-theme.export", :default => "Export")
      %table.table
        %tr
          %th{:sort => 'full_name', :class => 'sortable'}
            = t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th{:sort => 'score', :class => 'sortable'}
            = t("activerecord.attributes.admin_self_score.score", :default => t("activerecord.labels.rating", :default => "Rating"))
        - @scores.each do |line|
          %tr{:class => cycle("odd", "even")}
            %td
              = line.shift_leader.full_name
            %td
              = "%.2f" % line.avg_score
      .actions-bar.wat-cf
        .actions
        = will_paginate @scores
%div.modal#overlay
  %div.contentWrap