config/routes.rb
Personnel::Application.routes.draw do

  resources :taxi_routes, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resource :user do
      get :delivery, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_crop, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :notify_address, on: :collection
      get :notify_cell, on: :collection
      get :crop, on: :member
      get :find, on: :collection
      get :list, on: :collection
      put :send_notify_address, on: :collection
      put :send_notify_cell, on: :collection
  end

  resources :users do
    get :view, on: :member
    get :by_department, on: :collection
  end

  resources :addresses do
    get :make_primary, on: :member
    get :map, on: :member
    put :update_map, on: :member
  end

  resources :shifts do
    get :close_old, on: :collection
    get :check, on: :collection
    get :check_department_for_identifier, on: :member
    get :check_fired_permissions, on: :collection
  end
  resource :schedule do
    post :update_cell, on: :collection
    post :toggle_exclude, on: :collection
  end
  resources :vacation_requests
  resources :events do
    get :start_shift, on: :collection
    get :end_shift, on: :collection
    post :create_shift, on: :collection
    get :available_shift_numbers, on: :collection
    get :new_late_coming, on: :collection
    post :create_late_coming, on: :collection
    get :processed_by_person, on: :collection
    get :vacations, on: :collection
    get :new_self_score, on: :collection
    get :new_shift_leader_score, on: :collection
    post :create_self_score, on: :collection
    post :create_shift_leader_score, on: :collection
    get :list, on: :collection
  end
  resources :user_vehicles
  resources :late_comings
  resources :birthdays
  devise_for :admins, :controllers => { :registrations => "admin_registrations" }
  namespace :admin do
    root :to => "users#index"
    resources :departments, :categories, :schedule_statuses, :schedule_shifts, :permissions, :logs
    resources :late_comings do
      put :release, on: :collection
    end
    resources :admins do
      get :settings_edit, on: :collection
      put :settings_update, on: :collection
    end
    resource :schedule do
      get :show_users, on: :member
    end
    resources :schedule_cells do
      put :mass_update, on: :collection
      get :change, on: :collection
      get :batch_new, on: :collection
      put :batch_update, on: :collection
    end
    resources :shifts do
      get :available_shift_numbers, on: :collection
      get :missed, on: :collection
    end
    resources :events do
      get :processed_total, on: :collection
      get :processed_by_person, on: :collection
      get :vacations, on: :collection
      get :processed_by_day_of_week, on: :collection
      get :self_scores, on: :collection
      get :self_scores_grouped, on: :collection
      get :shift_leader_scores, on: :collection
      get :shift_leader_scores_grouped, on: :collection
    end
    resources :schedule_templates do
      post :set_visibility, on: :member
      get :select_users, on: :member
      put :update_editable_users, on: :member
      get :check_day, on: :member
      get :check_day_detailed, on: :member
      get :check_month, on: :member
      get :default_norms, on: :member
      get :user_norms, on: :member
      post :update_default_norms, on: :member
      post :update_user_norms, on: :member
      get :check_shift_interval, on: :member
    end

    resources :addresses do
      get :make_primary, on: :member
      get :map, on: :member
      put :update_map, on: :member
    end

    resources :users do
      get :delivery, on: :collection
      get :list, on: :collection
      get :find, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_permissions, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :crop, on: :member
      put :update_crop, on: :member
      put :clear_avatar, on: :member
      get :working_shifts, on: :collection
      get :t_shirts, on: :collection
      get :get_for_department, on: :collection
      put :update_for_department, on: :collection
      get :fire_reasons, on: :collection
      get :fired_people, on: :collection
    end

    resources :birthdays
    resources :fire_reasons
    resources :vacation_requests, only: [:index] do
      put :approve, on: :member
      put :decline, on: :member
    end
  end

  namespace :api do
    resources :departments, only: [:index, :show]
    resources :users, only: [:index] do
      get :rate, on: :collection
      get :rates, on: :collection
      get :feedbacks, on: :collection
      get :shifts, on: :collection
      get :nc_report, on: :collection
    end
    resources :leader_shifts, only: [:index]
  end

  root :to => "home#index"

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :department_permissions, :dependent => :destroy
  has_many :departments, :through => :department_permissions, :uniq => true

  has_many :user_permissions, :dependent => :destroy
  has_many :users, :through => :user_permissions, :uniq => true

  has_many :logs, :as => :subject

  validates_presence_of :name

  def self.selection
    order(:name).all.map do |d|
      [d.name, d.id]
    end
  end

  def self.in_columns
    arr = order(:name).all
    count_el_in_col = arr.length / 3
    arr.each_slice(count_el_in_col).to_a
  end

end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :check_permissions, :except => :delivery
  layout 'admin'

  def check_permissions
    redirect_to delivery_admin_users_path unless current_admin.super_user? || !current_admin.departments.empty?
  end

  def index
    @permissions = Permission.order(:name).all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @permissions }
    end
  end

  def new
    @permission = Permission.new
    render :layout => false
  end

  def create
    @permission = Permission.new(params[:permission])

    if @permission.save
      Log.add(current_admin, @permission, params)
      render(:update) do |page|
        page["#overlay"].dialog("close")
        page.call 'app.reload'
      end
    else
      message = '<p>' + @permission.errors.full_messages.join('</p><p>') + '</p>'
      render(:update) do |page|
        page['#permission_flash'].parents(0).show
        page['#permission_flash'].html message
      end
    end
  end

  def edit
    @permission = Permission.find(params[:id])
    render :layout => false
  end

  def update
    @permission = Permission.find(params[:id])
    params[:previous_attributes] = @permission.attributes
    if @permission.update_attributes(params[:permission])
      Log.add(current_admin, @permission, params)
      render(:update) do |page|
        page["#overlay"].dialog("close")
        page.call 'app.reload'
      end
    else
      message = '<p>' + @permission.errors.full_messages.join('</p><p>') + '</p>'
      render(:update) do |page|
        page['#permission_flash'].parents(0).show
        page['#permission_flash'].html message
      end
    end
  end

  def destroy
    @permission = Permission.find(params[:id])
    Log.add(current_admin, @permission, params)
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.xml { head :ok }
    end
  end
end

app/views/admin/permissions/_form.html.haml
%div{:class => "flash", :style => 'display:none;'}
  %div{:id => "permission_flash", :class => "message error"}
= form_for [:admin, @permission], :remote => true, :html => {:class => 'form', 'data-type' => 'script'} do |f|
  .group
    = f.label :name, t("activerecord.attributes.permission.name", :default => "Name:"), :class => :label
    = f.text_field :name, :class => 'text_field'
  .group.navform.wat-cf
    %button.button{:type => "submit"}
      = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
      = t("web-app-theme.save", :default => "Save")

    %a.button.close{:href => 'javascript:void(0);'}
      = image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}")
      = t("web-app-theme.cancel", :default => "Cancel")

app/views/admin/permissions/_sidebar.html.haml
.block.notice
  %h3 Tips
  .content
    %p The check list will allow you to keep track of all the accounts and systems users have access to.
    %p You can manage the list of all accounts/access/permissions here. Use Add tab to add a new account/permission. Make sure the name is clear and you can easily understand what it is for.
    %p
      Accounts are assigned to departments under
      =link_to("Departments", admin_departments_url)
      option and then added/deleted to/from the user on the user’s page under
      =link_to("Users", admin_users_url)
      option.

app/views/admin/permissions/edit.html.haml
%h1
  Edit Permission
= render 'form'

app/views/admin/permissions/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_permissions_path
      %li
        = link_to "#{t("web-app-theme.add", :default => "Add")}", new_admin_permission_path, :class => "modal_dialog"
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Accounts
    .inner
      %table.table
        %tr
          %th
            %b
              = t("activerecord.attributes.permission.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th.last &nbsp;
        - @permissions.each do |permission|
          %tr{:class => cycle("odd", "even")}
            %td
              = permission.name
            %td.last
              \#{link_to "#{t("web-app-theme.edit", :default => "Logs")}", admin_logs_path(:subject_type => 'Permission', :subject_id => permission.id)}
              |
              #{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_permission_path(permission), :class => "modal_dialog"} |
              #{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_permission_path(permission), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure you would like to delete #{permission.name} permission?")}"}
- content_for :sidebar, render(:partial => 'sidebar')
%div.modal#overlay
  %div.contentWrap

app/views/admin/permissions/new.html.haml
%h1
  New Permission
= render 'form'