config/routes.rb
Personnel::Application.routes.draw do

  resources :taxi_routes, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resource :user do
      get :delivery, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_crop, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :notify_address, on: :collection
      get :notify_cell, on: :collection
      get :crop, on: :member
      get :find, on: :collection
      get :list, on: :collection
      put :send_notify_address, on: :collection
      put :send_notify_cell, on: :collection
  end

  resources :users do
    get :view, on: :member
    get :by_department, on: :collection
  end

  resources :addresses do
    get :make_primary, on: :member
    get :map, on: :member
    put :update_map, on: :member
  end

  resources :shifts do
    get :close_old, on: :collection
    get :check, on: :collection
    get :check_department_for_identifier, on: :member
    get :check_fired_permissions, on: :collection
  end
  resource :schedule do
    post :update_cell, on: :collection
    post :toggle_exclude, on: :collection
  end
  resources :vacation_requests
  resources :events do
    get :start_shift, on: :collection
    get :end_shift, on: :collection
    post :create_shift, on: :collection
    get :available_shift_numbers, on: :collection
    get :new_late_coming, on: :collection
    post :create_late_coming, on: :collection
    get :processed_by_person, on: :collection
    get :vacations, on: :collection
    get :new_self_score, on: :collection
    get :new_shift_leader_score, on: :collection
    post :create_self_score, on: :collection
    post :create_shift_leader_score, on: :collection
    get :list, on: :collection
  end
  resources :user_vehicles
  resources :late_comings
  resources :birthdays
  devise_for :admins, :controllers => { :registrations => "admin_registrations" }
  namespace :admin do
    root :to => "users#index"
    resources :departments, :categories, :schedule_statuses, :schedule_shifts, :permissions, :logs
    resources :late_comings do
      put :release, on: :collection
    end
    resources :admins do
      get :settings_edit, on: :collection
      put :settings_update, on: :collection
    end
    resource :schedule do
      get :show_users, on: :member
    end
    resources :schedule_cells do
      put :mass_update, on: :collection
      get :change, on: :collection
      get :batch_new, on: :collection
      put :batch_update, on: :collection
    end
    resources :shifts do
      get :available_shift_numbers, on: :collection
      get :missed, on: :collection
    end
    resources :events do
      get :processed_total, on: :collection
      get :processed_by_person, on: :collection
      get :vacations, on: :collection
      get :processed_by_day_of_week, on: :collection
      get :self_scores, on: :collection
      get :self_scores_grouped, on: :collection
      get :shift_leader_scores, on: :collection
      get :shift_leader_scores_grouped, on: :collection
    end
    resources :schedule_templates do
      post :set_visibility, on: :member
      get :select_users, on: :member
      put :update_editable_users, on: :member
      get :check_day, on: :member
      get :check_day_detailed, on: :member
      get :check_month, on: :member
      get :default_norms, on: :member
      get :user_norms, on: :member
      post :update_default_norms, on: :member
      post :update_user_norms, on: :member
      get :check_shift_interval, on: :member
    end

    resources :addresses do
      get :make_primary, on: :member
      get :map, on: :member
      put :update_map, on: :member
    end

    resources :users do
      get :delivery, on: :collection
      get :list, on: :collection
      get :find, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_permissions, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :crop, on: :member
      put :update_crop, on: :member
      put :clear_avatar, on: :member
      get :working_shifts, on: :collection
      get :t_shirts, on: :collection
      get :get_for_department, on: :collection
      put :update_for_department, on: :collection
      get :fire_reasons, on: :collection
      get :fired_people, on: :collection
    end

    resources :birthdays
    resources :fire_reasons
    resources :vacation_requests, only: [:index] do
      put :approve, on: :member
      put :decline, on: :member
    end
  end

  namespace :api do
    resources :departments, only: [:index, :show]
    resources :users, only: [:index] do
      get :rate, on: :collection
      get :rates, on: :collection
      get :feedbacks, on: :collection
      get :shifts, on: :collection
      get :nc_report, on: :collection
    end
    resources :leader_shifts, only: [:index]
  end

  root :to => "home#index"

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates_presence_of :name

  has_many :admin_departments, :dependent => :destroy
  has_many :admins, :through => :admin_departments, :uniq => true

  has_many :department_permissions, :dependent => :destroy
  has_many :permissions, :through => :department_permissions, :uniq => true

  has_many :department_categories, :dependent => :destroy
  has_many :categories, :through => :department_categories, :uniq => true

  has_many :logs, :as => :subject

  scope :identified, where('has_identifier = 1')

  def self.search(params, admin_id)
    params[:sort_by] ||= :name
    admin = Admin.find_by_id(admin_id)
    conditions = []
    conditions.push("id IN (#{admin.departments.map{|d|d.id}.join(',')})") unless admin.super_user?
    paginate :per_page => [params[:per_page].to_i, 5].max, :page => params[:page],
             :conditions => conditions.join(' and '),
             :order => "#{params[:sort_by]} #{params[:sort_order]}"
  end

  def self.selection(tracked_only = false)
    order(:name).all.map do |d|
      next if tracked_only and not d.has_events?
      [d.name, d.id]
    end.compact
  end

  def self.selection_by_admin(admin_id, tracked_only = false)
    admin = Admin.find_by_id(admin_id)
    return selection(tracked_only) if admin.super_user?
    departments = admin.departments.map(&:id)
    admin.departments.order(:name).all.map do |d|
      if departments.include?(d.id)
        next if tracked_only and not d.has_events?
        [d.name, d.id]
      end
    end.compact
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :check_permissions
  layout 'admin'

  def check_permissions
    redirect_to delivery_admin_users_path unless current_admin.super_user? || !current_admin.departments.empty?
  end

  # GET /departments
  # GET /departments.xml
  def index
    params[:per_page] ||= current_admin.admin_settings.find_or_create_by_key('per_page').value
    params[:per_page] ||= 15
    #@departments = Department.paginate :page => params[:page], :per_page => params[:per_page], :order => "#{params[:sort_by]} #{params[:sort_order]}"
    @departments = Department.search(params, current_admin.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.xml
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.xml
  def new
    if !current_admin.super_user?
      flash[:error] = "You dont have permissions to view this page"
      redirect_to admin_departments_path  and return
    end
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
    redirect_to admin_departments_path unless current_admin.manage_department(@department.id)
  end

  # POST /departments
  # POST /departments.xml
  def create
    if !current_admin.super_user?
      flash[:error] = "You dont have permissions to view this page"
      redirect_to admin_departments_path  and return
    end
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        Log.add(current_admin, @department, params)
        if params[:permissions].is_a? Array
          params[:permissions].each do |d|
            DepartmentPermission.find_or_create_by_department_id_and_permission_id(@department.id,d.to_i)
          end
        end
        format.html { redirect_to([:admin, @department], :notice => 'Department was successfully created.') }
        format.xml  { render :xml => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.xml
  def update
    @department = Department.find(params[:id])
    redirect_to admin_departments_path and return unless current_admin.manage_department(@department.id)
    params[:previous_attributes] = @department.attributes

    old_permissions = @department.permissions.map{|d|d.id.to_s}
    if old_permissions != params[:permissions]
      old_permissions.each do |d|
        unless (params[:permissions].is_a?(Array) && params[:permissions].include?(d))
          users = User.find_all_by_department_id @department.id
          users.each do |u|
            up = UserPermission.find_by_user_id_and_permission_id(u.id, d.to_i)
            up.destroy unless up.nil?
          end
          DepartmentPermission.find_by_department_id_and_permission_id(@department.id,d.to_i).destroy
        end
      end
      if params[:permissions]
        new_permissions = params[:permissions] - old_permissions
        new_permissions.each do |d|
          DepartmentPermission.find_or_create_by_department_id_and_permission_id(@department.id,d.to_i)
        end
      end
    end

    respond_to do |format|
      if @department.update_attributes(params[:department])
        Log.add(current_admin, @department, params)
        format.html { redirect_to([:admin, @department], :notice => 'Department was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.xml
  def destroy
    @department = Department.find(params[:id])
    redirect_to admin_departments_path and return unless current_admin.manage_department(@department.id)
    Log.add(current_admin, @department, params)
    @department.destroy

    respond_to do |format|
      format.html { redirect_to(admin_departments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/api/departments_controller.rb
class Api::DepartmentsController < Api::BaseController

  def index
    @departments = Department.all.inject([]) do |res, i|
      res << {id: i.id, name: i.name}
      res
    end
    respond_to do |format|
      format.json { render json: @departments }
    end
  end

  def show
    error!('Missing required parameter: month', 404) and return unless params[:month]
    error!('Missing required parameter: year', 404) and return unless params[:year]

    template = ScheduleTemplate.find_by_department_id_and_month_and_year(params[:id], params[:month], params[:year])
    error!('Schedule not found', 404) and return unless template
    user_ids, newbies = [], []
    template.schedule_shifts.where("number < 10").each do |shift|
      user_ids = user_ids + shift.schedule_cells.where("additional_attributes != 13 OR additional_attributes IS NULL").map(&:user_id)
      newbies = newbies + shift.schedule_cells.where(additional_attributes: 2).map(&:user_id)
    end
    respond_to do |format|
      format.json { render json: {total: user_ids.uniq.size, newbies: newbies.uniq.size} }
    end
  end
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.haml
.group
  = f.label :name, t("web-app-theme.name", :default => "Name"), :class => :label
  = f.text_field :name, :class => 'text_field'
.group
  = f.label :has_identifier, t("personnel.department.has-identifier", :default => "Has identifier"), :class => :label
  = f.check_box :has_identifier, :class => 'check_box'
  %span.description check this box if members of the department have unique identifiers/numbers
.group
  = f.label :has_events, t("personnel.department.has-events", :default => "Track TR Events"), :class => :label
  = f.check_box :has_events, :class => 'check_box'
  %span.description check this box if members of this department add events to Time Report
.group
  = f.label :self_scored, t("personnel.department.self_scored", :default => "Self Scored"), :class => :label
  = f.check_box :self_scored, :class => 'check_box'
  %span.description check this box if members of this department score themselves
.group
  = f.label :has_t_shirt, t("personnel.department.has-t-shirt", :default => "Has T-shirts"), :class => :label
  = f.check_box :has_t_shirt, :class => 'check_box'
  %span.description check this box if the department offers T-Shirts
.group
  = f.label :has_levels, t("personnel.department.has-levels", :default => "Has Levels"), :class => :label
  = f.check_box :has_levels, :class => 'check_box'
  %span.description check this box if the department has levels
.group
  = f.label :has_schedule, t("personnel.department.has-schedule", :default => "Has Schedule"), :class => :label
  = f.check_box :has_schedule, :class => 'check_box'
  %span.description check this box if the department has schedule
.group
  = f.label :show_address, t("personnel.department.show-address", :default => "Show Address"), :class => :label
  = f.check_box :show_address, :class => 'check_box'
  %span.description check this box if the department allows to show member's address
.group
  = f.label :vacation_norm, 'Vacation Norm', :class => :label
  = f.text_field :vacation_norm, :class => 'text_field'
.group.navform.wat-cf{:id => "check_list"}
  = f.label :permissions, t("personnel.department.assigned-accounts", :default => "Assigned Accounts"), :class => :label
  = link_to t("web-app-theme.check-all", :default => "Check All"), "#", :id => "check_all"
  |
  = link_to t("web-app-theme.uncheck-all", :default => "Uncheck All"), "#", :id => "uncheck_all"
  %br
  %br
  - Permission.in_columns.each do |col|
    %div{:style => "width:300px;float:left"}
      - col.each do |item|
        %div{:style => "width:300px;float:left"}
          = check_box_tag "permissions[]", "#{item.id}", @department.permissions.include?(item), :department => @department.id
          = item.name

.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + t("web-app-theme.cancel", :default => "Cancel"), admin_departments_path, :class => "button"

  = hidden_field :department, :id

%div.modal#overlay
  %div.contentWrap

app/views/admin/departments/_sidebar.html.haml
.block.notice
  %h3 Tips
  .content
    %p Here you сan manage departments assigned to you.
    %p Users of each department may have identifiers (unique number), t-shirts (they will be asked for their size) and levels (can be changed by admin only, but is visible to the user).
    %p
      %b Assigned Accounts
      option allows you to select different accounts (access) that are applicable for the department. List of such accounts can be changed under
      = link_to("Check List", admin_permissions_url)
      option and is managed separately for each user under
      = link_to("Users section", admin_users_url)

app/views/admin/departments/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_departments_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_department_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_department_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      = t("personnel.department.title-single", :default => "Department")
    .inner
      = render "shared/form_errors", :object => @department
      = form_for @department, :url => admin_department_path(@department), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/departments/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_departments_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_department_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      =t("personnel.department.title", :default => "Departments")
    .inner
      = form_tag(admin_departments_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
      %table.table
        %tr
          %th.first ID
          %th{:sort => 'name', :class => 'sortable'}
            = t("web-app-theme.name", :default => "Name")
          %th
            =t("personnel.admin.title", :default => "Admins")
          %th{:sort => 'created_at', :class => 'sortable'}
            = t("web-app-theme.created-at", :default => "Created on")
          %th.last &nbsp;
        - @departments.each do |department|
          %tr{:class => cycle("odd", "even")}
            %td
              = department.id
            %td
              = link_to department.name+" (#{User.find_all_by_department_id_and_active(department.id, 1).size})", admin_department_path(department)
            %td
              - department.admins.each do |admin|
                = admin.email
                %br
            %td
              = department.created_at.to_formatted_s(:date_and_time)
            %td.last
              \#{link_to "#{t("web-app-theme.logs", :default => "Logs")}", admin_logs_path(:subject_type => 'Department', :subject_id => department.id)}
              |
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_department_path(department)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_department_path(department)}
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_department_path(department), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure you would like to delete #{department.name} department?")}"}
      .actions-bar.wat-cf
        .actions
        = will_paginate @departments
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/departments/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_departments_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_department_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      = t("personnel.department.title-single", :default => "Department")
    .inner
      = render "shared/form_errors", :object => @department
      = form_for :department, :url => admin_departments_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/departments/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_departments_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_department_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_department_path
  .content
    .inner
      %h1
        = @department.name
      %p
        %b
          = t("activerecord.attributes.admin_department.has_identifier", :default => t("activerecord.labels.has_identifier", :default => "Has identifier"))
          \:
        = @department.has_identifier
      %p
        %b
          = t("activerecord.attributes.admin_department.has_events", :default => t("activerecord.labels.has_events", :default => "Has events"))
          \:
        = @department.has_events
      %p
        %b
          = t("activerecord.attributes.admin_department.self_scored", :default => t("activerecord.labels.self_scored", :default => "Self Scored"))
          \:
        = @department.self_scored
      %p
        %b
          = t("activerecord.attributes.admin_department.has_levels", :default => t("activerecord.labels.has_levels", :default => "Has Levels"))
          \:
        = @department.has_levels
      %p
        %b
          = t("activerecord.attributes.admin_department.has_schedule", :default => t("activerecord.labels.has_schedule", :default => "Has Schedule"))
          \:
        = @department.has_schedule
      %p
        %b
          = t("activerecord.attributes.admin_department.has_t_shirt", :default => t("activerecord.labels.has_t_shirt", :default => "Has T-Shirts"))
          \:
        = @department.has_t_shirt
      - if !@department.permissions.empty?
        %p
          %b
            = t("activerecord.attributes.admin_department.permissions", :default => t("activerecord.labels.permissions", :default => "Permissions"))
            \:
          %ul{:style => "margin-left:20px"}
            - @department.permissions.each do |d|
              %li
                = d.name
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_department_path(@department), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_department_path(@department), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')