config/routes.rb
Personnel::Application.routes.draw do

  resources :taxi_routes, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resource :user do
      get :delivery, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_crop, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :notify_address, on: :collection
      get :notify_cell, on: :collection
      get :crop, on: :member
      get :find, on: :collection
      get :list, on: :collection
      put :send_notify_address, on: :collection
      put :send_notify_cell, on: :collection
  end

  resources :users do
    get :view, on: :member
    get :by_department, on: :collection
  end

  resources :addresses do
    get :make_primary, on: :member
    get :map, on: :member
    put :update_map, on: :member
  end

  resources :shifts do
    get :close_old, on: :collection
    get :check, on: :collection
    get :check_department_for_identifier, on: :member
    get :check_fired_permissions, on: :collection
  end
  resource :schedule do
    post :update_cell, on: :collection
    post :toggle_exclude, on: :collection
  end
  resources :vacation_requests
  resources :events do
    get :start_shift, on: :collection
    get :end_shift, on: :collection
    post :create_shift, on: :collection
    get :available_shift_numbers, on: :collection
    get :new_late_coming, on: :collection
    post :create_late_coming, on: :collection
    get :processed_by_person, on: :collection
    get :vacations, on: :collection
    get :new_self_score, on: :collection
    get :new_shift_leader_score, on: :collection
    post :create_self_score, on: :collection
    post :create_shift_leader_score, on: :collection
    get :list, on: :collection
  end
  resources :user_vehicles
  resources :late_comings
  resources :birthdays
  devise_for :admins, :controllers => { :registrations => "admin_registrations" }
  namespace :admin do
    root :to => "users#index"
    resources :departments, :categories, :schedule_statuses, :schedule_shifts, :permissions, :logs
    resources :late_comings do
      put :release, on: :collection
    end
    resources :admins do
      get :settings_edit, on: :collection
      put :settings_update, on: :collection
    end
    resource :schedule do
      get :show_users, on: :member
    end
    resources :schedule_cells do
      put :mass_update, on: :collection
      get :change, on: :collection
      get :batch_new, on: :collection
      put :batch_update, on: :collection
    end
    resources :shifts do
      get :available_shift_numbers, on: :collection
      get :missed, on: :collection
    end
    resources :events do
      get :processed_total, on: :collection
      get :processed_by_person, on: :collection
      get :vacations, on: :collection
      get :processed_by_day_of_week, on: :collection
      get :self_scores, on: :collection
      get :self_scores_grouped, on: :collection
      get :shift_leader_scores, on: :collection
      get :shift_leader_scores_grouped, on: :collection
    end
    resources :schedule_templates do
      post :set_visibility, on: :member
      get :select_users, on: :member
      put :update_editable_users, on: :member
      get :check_day, on: :member
      get :check_day_detailed, on: :member
      get :check_month, on: :member
      get :default_norms, on: :member
      get :user_norms, on: :member
      post :update_default_norms, on: :member
      post :update_user_norms, on: :member
      get :check_shift_interval, on: :member
    end

    resources :addresses do
      get :make_primary, on: :member
      get :map, on: :member
      put :update_map, on: :member
    end

    resources :users do
      get :delivery, on: :collection
      get :list, on: :collection
      get :find, on: :collection
      get :edit_data, on: :member
      put :update_data, on: :member
      put :update_permissions, on: :member
      get :display_addresses, on: :member
      get :display_section, on: :member
      get :crop, on: :member
      put :update_crop, on: :member
      put :clear_avatar, on: :member
      get :working_shifts, on: :collection
      get :t_shirts, on: :collection
      get :get_for_department, on: :collection
      put :update_for_department, on: :collection
      get :fire_reasons, on: :collection
      get :fired_people, on: :collection
    end

    resources :birthdays
    resources :fire_reasons
    resources :vacation_requests, only: [:index] do
      put :approve, on: :member
      put :decline, on: :member
    end
  end

  namespace :api do
    resources :departments, only: [:index, :show]
    resources :users, only: [:index] do
      get :rate, on: :collection
      get :rates, on: :collection
      get :feedbacks, on: :collection
      get :shifts, on: :collection
      get :nc_report, on: :collection
    end
    resources :leader_shifts, only: [:index]
  end

  root :to => "home#index"

end

app/views/admin/admins/_form.html.haml
.group
  = f.label :super_user, t("personnel.admin.super-user", :default => "Super User"), :class => :label
  = f.check_box :super_user, :class => 'check_box'
.group
  = f.label :approved, t("personnel.admin.approved", :default => "Approved"), :class => :label
  = f.check_box :approved, :class => 'check_box'
.group
  = f.label :email, t("personnel.user.email", :default => "Email"), :class => :label
  = f.text_field :email, :class => 'text_field'
  %span.description= t("personnel.user.Please use your zone3000 email address", :default => 'Please use your zone3000 email address')
.group
  = f.label :password, t("personnel.user.password", :default => "Password"), :class => :label
  = f.password_field :password, :class => 'text_field'
.group
  = f.label :confirm_password, t("personnel.user.password_confirmation", :default => "Confirm Password"), :class => :label
  = f.password_field :password_confirmation, :class => 'text_field'
-#.group
-#  = f.label :departments, t("activerecord.attributes.admin.departments", :default => "Assigned Departments"), :class => :label
-#  = select_tag 'departments[]', options_for_select(Department.selection, @admin.departments.map(&:id)), { :multiple => true, :size =>Department.selection.size }
.group
  = f.label :departments, t("personnel.admin.assigned-departments", :default => "Assigned Departments"), :class => :label
  - Department.selection.each do |d|
    = check_box_tag "departments[]", d.last, @admin.departments.map(&:id).include?(d.last)
    = d.first
    %br

.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + t("web-app-theme.cancel", :default => "Cancel"), admin_admins_path, :class => "button"

app/views/admin/admins/_sidebar.html.haml
.block.notice
  %h3 Tips
  .content
    %p You can manage admin users here.
    %p Several departments can be assigned to one admin user. This will allow admin user to manage users, schedule, and time report within the assigned department(s) only.

app/views/admin/admins/_sidebar_settings_edit.html.haml
.block.notice
  %h3 Tips
  .content
    %p The number of items per page you set here will be automatically applied to all the pages within this admin panel. You will still have an option to change the number of items per page on a specific page separately.

app/views/admin/admins/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_admins_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_admin_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_admin_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      = t("personnel.admin.title-single-whom", :default => "Admin")
    .inner
      = render "shared/form_errors", :object => @admin
      = form_for @admin, :url => admin_admin_path(@admin), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/admins/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_admins_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_admin_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      = t("personnel.admin.title", :default => "Admins")
    .inner
      = form_tag(admin_admins_path, :method => :get, :id => 'find_form') do
        %table
          %tr
            %td
              = hidden_field_tag 'sort_by', params[:sort_by]
              = hidden_field_tag 'sort_order', params[:sort_order]
      %table.table
        %tr
          %th.first ID
          %th
            =t("personnel.admin.super-user", :default => "Super User")
          %th
            =t("personnel.admin.approved", :default => "Approved")
          %th{:sort => 'email', :class => 'sortable'}
            = t("activerecord.attributes.admin_admin.email", :default => t("activerecord.labels.email", :default => "Email"))
          %th
            =t("personnel.admin.assigned-departments", :default => "Assigned Departments")
          %th{:sort => 'created_at', :class => 'sortable'}
            = t("web-app-theme.created-at", :default => "Created on")
          %th.last &nbsp;
        - @admins.each do |admin|
          %tr{:class => cycle("odd", "even")}
            %td
              = admin.id
            %td
              - if admin.super_user
                &#10003;
            %td
              - if admin.approved
                &#10003;
            %td
              = link_to admin.email, admin_admin_path(admin)
            %td
              - admin.departments.each do |d|
                = d.name
                %br
            %td
              = admin.created_at.to_formatted_s(:date_and_time)
            %td.last
              \#{link_to "#{t("web-app-theme.logs", :default => "Logs")}", admin_logs_path(:author_type => 'Admin', :author_id => admin.id)}
              |
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_admin_path(admin)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_admin_path(admin)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_admin_path(admin), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure you would like to delete #{admin.name} admin?")}"}
      .actions-bar.wat-cf
        .actions
        = will_paginate @admins
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/admins/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_admins_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_admin_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      = t("personnel.admin.title-single", :default => "Admin")
    .inner
      = render "shared/form_errors", :object => @admin
      = form_for :admin, :url => admin_admins_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/admins/settings_edit.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Settings
    .inner
      = form_tag(settings_update_admin_admins_path, :method => :put, :html => { :class => :form }) do
        - AdminSetting.selection.each do |key,label|
          .group
            = label
            = text_field_tag "settings[#{key}]", @admin.admin_settings.find_or_create_by_key(key).value, :class => 'text_field'
        %br
        .group.navform.wat-cf
          %button.button{:type => "submit"}
            = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
            = t("web-app-theme.save", :default => "Save")
          %span.text_button_padding= t("web-app-theme.or", :default => "or")
          = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + t("web-app-theme.cancel", :default => "Cancel"), admin_admins_path, :class => "button"
- content_for :sidebar, render(:partial => 'sidebar_settings_edit')

app/views/admin/admins/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_admins_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_admin_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_admin_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.admin_admin.email", :default => t("activerecord.labels.email", :default => "Email"))
          \:
        = @admin.email
      %p
        %b
          = t("activerecord.attributes.admin_admin.sign_in_count", :default => t("activerecord.labels.sign_in_count", :default => "Sign in count"))
          \:
        = @admin.sign_in_count
      %p
        %b
          = t("activerecord.attributes.admin_admin.current_sign_in_at", :default => t("activerecord.labels.current_sign_in_at", :default => "Current sign in at"))
          \:
        = @admin.current_sign_in_at
      %p
        %b
          = t("activerecord.attributes.admin_admin.last_sign_in_at", :default => t("activerecord.labels.last_sign_in_at", :default => "Last sign in at"))
          \:
        = @admin.last_sign_in_at
      %p
        %b
          = t("activerecord.attributes.admin_admin.current_sign_in_ip", :default => t("activerecord.labels.current_sign_in_ip", :default => "Current sign in ip"))
          \:
        = @admin.current_sign_in_ip
      %p
        %b
          = t("activerecord.attributes.admin_admin.last_sign_in_ip", :default => t("activerecord.labels.last_sign_in_ip", :default => "Last sign in ip"))
          \:
        = @admin.last_sign_in_ip
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_admin_path(@admin), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_admin_path(@admin), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/admins/sign_up.html.haml
%h1 Zone3000 Staff
.block#block-login
  %h2 Sign up
  .content.login
    .flash
      - resource.errors.each do |type, message|
        %div{ :class => "message error" }
          %p= "#{type.to_s.capitalize} #{message}"
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :class => "form login" }) do |f|
      .group.wat-cf
        .left= f.label :email, :class => "label right"
        .right= f.email_field :email, :class => "text_field"
      .group.wat-cf
        .left= f.label :password, :class => "label right"
        .right= f.password_field :password, :class => "text_field"
      .group.wat-cf
        .left= f.label :password_confirmation, :class => "label right"
        .right= f.password_field :password_confirmation, :class => "text_field"
      .group.wat-cf
        .left= f.label :department_id, :class => "label right"
        .right= f.select :department_id, Department.all.collect {|d| [ d.name, d.id ] }, :class => "text_field"
      .group.wat-cf
        .left= f.label :identifier, :class => "label right"
        .right= f.select :identifier, User.identifier_selection(nil), :class => "text_field", :include_blank => true
      .group.wat-cf
        .right
          %button.button{ :type => "submit" }
            = image_tag "web-app-theme/icons/key.png"
            Sign up
    = render :partial => "devise/shared/links"